### ISSUE TITLE
MAE does not support experiments with BiocFrame col_data

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/MultiAssayExperiment#13]
https://github.com/BiocPy/MultiAssayExperiment/blob/6a1d7d1854078cd37063f5c95140953f61d35d7e/src/multiassayexperiment/MultiAssayExperiment.py#L179

MAE also does not support BiocFrame col_data (you'll have to fix all the type hinting as well):

https://github.com/BiocPy/MultiAssayExperiment/blob/6a1d7d1854078cd37063f5c95140953f61d35d7e/src/multiassayexperiment/MultiAssayExperiment.py#L135

Prolly other issues related to BiocFrame, not bother ing to find them all.

**Comment by jkanche** [comment]
I believe with #17 merged, this is not necessary anymore.  Please reopen if the issue persists.
